[tool.poetry]
name = "meshboi"
version = "0.1.0"
description = ""
authors = ["Leslie Leung <lesily9@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
meshtastic = "^2.5.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
